# Generated by Django 3.1.3 on 2021-06-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAdministrador', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JefeAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJefe', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecepcionista', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTecnico', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=200)),
                ('cantidad', models.CharField(max_length=50)),
                ('tipo_pedido', models.CharField(max_length=50)),
                ('Camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.camion')),
                ('JefeAlmacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.jefealmacen')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.marca')),
                ('Tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.tecnico')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.administrador')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('Camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.camion')),
                ('Conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.conductor')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptaller.recepcionista')),
            ],
        ),
    ]
