# Generated by Django 3.1.3 on 2021-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptaller', '0002_auto_20210608_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Aprobado'), (2, 'Por Aprobar')]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.IntegerField(choices=[(1, 'Solicitud de Permiso de Repuestos'), (2, 'Solicitud de Comprar Nuevos Repuestos')]),
        ),
    ]
